name: Build macOS DMG

on:
  workflow_dispatch: # manually trigger karne ke liye
  push:
    branches: [ "main" ] # jab tu main branch push kare

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build dmg
        run: npm run build:mac

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mac-dmg
          path: dist/*.dmg
